#!/bin/bash

dir=$(pwd)
while ! [ -f $dir/syncsrc.rc ]
do
	if [ -z $dir ] ; then echo ~~ config not found ~~ ; exit 1; fi
	dir=$(dirname $dir)
done

wd=$(basename $dir)
dir=$(dirname $dir)

#call config file
#it set all rsync stuff
#$RSYNC point to all command and args
#$remote has an remote address
# syncsrc.rc should be in working(!) dir
. $dir/$wd/syncsrc.rc
echo remote is $remote
echo remote host is $remote_host
echo remote folder is $remote_path
echo

host=$(hostname)
macine=$(cat /etc/machine-id | sha256sum | cut -c 1-64)
seat=$host-$macine

mkdir -p $dir/.seats/$wd

case "$1" in
"pull" )
echo ~~ pull ~~
echo
rsync_command -utWxvd --delete --exclude /$seat \
	$remote_host:$remote_path/.seats/$wd/ $dir/.seats/$wd/
latest=$(ls -t $dir/.seats/$wd/*-* | head -1)
if [ "$latest" != "$dir/.seats/$wd/$seat" ]
then
	echo
	echo ~~ incoming changes found ~~
	echo
	rsync_command -av --delete $remote_host:$remote_path/$wd/ $dir/$wd/
else
	echo ~~ files here are newer ~~
fi
;;
"push" )
echo ~~ push ~~
echo
#push changes to remove site
rsync_command -utWxvd --delete --exclude /$seat \
	$remote_host:$remote_path/.seats/$wd/ $dir/.seats/$wd/
latest=$(ls -t $dir/.seats/$wd/*-* | head -1)
if [ "$latest" == "$dir/.seats/$wd/$seat" ]
then
	rsync_command -av --delete $dir/.seats/$wd/ $remote_host:$remote_path/.seats/$wd/
	rsync_command -av --delete $dir/$wd/ $remote_host:$remote_path/$wd/
fi
;;
"push-init" )
echo ~~ initial push ~~
echo
	rsync_command -av --delete $dir/.seats/$wd/ $remote_host:$remote_path/.seats/$wd/
	rsync_command -av --delete $dir/$wd/ $remote_host:$remote_path/$wd/
;;
esac
echo
echo ~~ ok ~~

